#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        # Loopback
        iif lo accept

        # Established/related
        ct state established,related accept

        # ICMP (ping)
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        # SSH apenas do desktop admin
        tcp dport 22 ip saddr 172.16.254.248 accept

        # Porta 87 (Apache) apenas do nginx reverse proxy
        tcp dport 87 ip saddr 172.16.0.96 accept

        # Log e descarta o resto
        log prefix "[nftables INPUT] " drop
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
